version: "3"
services:
  task-b:
    image: ken109/laravel
    restart: always
    container_name: task-b
    ports:
      - "8001:80"
    environment:
      LARAVEL_NAME: task-b
      LARAVEL_ENV: local
      LARAVEL_DB_HOST: host.docker.internal
      LARAVEL_DB_USER: sha2
      LARAVEL_DB_PASSWORD: password
      LARAVEL_DB_NAME: task-b
    volumes:
      - .:/var/www/html
